### ISSUE TITLE
Code is not displayed correctly in home preview

### ISSUE THREAD

**Issue by Nhoya** [dillonzq/LoveIt#2]
Hi,
seems that posts containing code in the home preview are displayed incorrectly:

Home:
![immagine](https://user-images.githubusercontent.com/7293260/69486880-54703100-0e51-11ea-9283-76f4b82fb199.png)
Post:
![immagine](https://user-images.githubusercontent.com/7293260/69486883-59cd7b80-0e51-11ea-9b0a-275c5c2a9c76.png)

**Comment by flowchartsman** [comment]
This is probably because you are not manually splitting your post with `<!--more-->`, so Hugo is automatically generating a summary and stripping the HTML: 

https://discourse.gohugo.io/t/summary-page-shows-the-content-of-shortcode-script-html-element/18444/2
https://gohugo.io/content-management/summaries/

Try manually splitting the post and see what happens.

**Comment by Nhoya** [comment]
this fixed the issue, thanks
