### ISSUE TITLE
Modify title text presentation

### ISSUE THREAD

**Issue by Eliesemoule** [dillonzq/LoveIt#35]
Hello,

By default, the title texts are written from right to left. Is it possible to modify the theme so that the title texts are written from left to right?

Thanks,

<img width="858" alt="Capture d’écran 2020-01-06 à 11 30 24" src="https://user-images.githubusercontent.com/20320541/71812760-57795680-3078-11ea-8250-3170f1677d06.png">

**Comment by jbfreels** [comment]
If I'm understanding correctly, you can add...

```css
.single .post-title {
  text-align: left;
}
```

to `themes/LoveIt/assets/css/_custom.scss`

**Comment by dillonzq** [comment]
Since the [`fb7aa91` commit](https://github.com/dillonzq/LoveIt/commit/fb7aa91d155b99faab6154c7d51361b4160cbc49) commit, `config/css/_custom.scss` in your project is the new path of custom style file to ensure the integrity of the theme directory.
A sample file of `config/css/_custom.scss` is in the `exampleSite`.
