### ISSUE TITLE
[BUG] 矩阵渲染的错误

### ISSUE THREAD

**Issue by Lraxer** [dillonzq/LoveIt#561]
### Describe the bug 描述你遇到的错误

使用矩阵的bmatrix, pmatrix等环境时出错

### Expected behavior 期待的行为

输入这样的代码
```
A =
\begin{bmatrix} 
a_{i1}^1 & a_{i1}^2 & \cdots & a_{i1}^l \\
a_{i2}^1 & a_{i2}^2 & \cdots & a_{i2}^l \\
\vdots & \vdots & & \vdots \\
a_{ir}^1 & a_{ir}^2 & \cdots & a_{ir}^l \\
\end{bmatrix}
```
不能正常渲染。必须要把矩阵的代码写在一行，并且使用4个反斜线才能渲染，如下：
```
A =
\begin{bmatrix} a_{i1}^1 & a_{i1}^2 & \cdots & a_{i1}^l \\\\ a_{i2}^1 & a_{i2}^2 & \cdots & a_{i2}^l \\\\ \vdots & \vdots & & \vdots \\\\ a_{ir}^1 & a_{ir}^2 & \cdots & a_{ir}^l \\\\ \end{bmatrix}
```

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/32860114/100562132-b2054c00-32f5-11eb-80fe-ee9930fa8d5f.png)

### Build Environment 构建环境

- OS: [Windows 10]
- Theme version [0.2.10]
- Hugo version [0.78.2]

**Comment by uPagge** [comment]
@Lraxer Since the developer has unfortunately abandoned the project :disappointed:, I would like to take responsibility for its support and development in the future.

I focused on adding new features, refreshed the design of the posts, fixed the bugs I found. 
There were so many changes (the ability to choose a separate design for the post, breadcrumbs, a new comment system and much more), and so much to do, that I decided to give the template a **new name uBlogger.**

**I will be glad if you look at it, you may like the updated design.**
-- -- -- -- --
:link: -> https://github.com/uPagge/uBlogger.

**Comment by victor-pogor** [comment]
Hi @Lraxer.

Can you try to wrap your code between `<p>...</p>`  tags?

```LaTeX
<p>
$$
A =
  \begin{bmatrix} a_{i1}^1 & a_{i1}^2 & \cdots & a_{i1}^l \\
  a_{i2}^1 & a_{i2}^2 & \cdots & a_{i2}^l \\
  \vdots & \vdots & & \vdots \\
  a_{ir}^1 & a_{ir}^2 & \cdots & a_{ir}^l \\
\end{bmatrix}
$$
</p>
```

---
🔗[https://github.com/sunt-programator/CodeIT](https://github.com/sunt-programator/CodeIT)

**Comment by Lraxer** [comment]
> Hi @Lraxer.
> 
> Can you try to wrap your code between `<p>...</p>` tags?
> 
> ```
> <p>
> $$
> A =
>   \begin{bmatrix} a_{i1}^1 & a_{i1}^2 & \cdots & a_{i1}^l \\
>   a_{i2}^1 & a_{i2}^2 & \cdots & a_{i2}^l \\
>   \vdots & \vdots & & \vdots \\
>   a_{ir}^1 & a_{ir}^2 & \cdots & a_{ir}^l \\
> \end{bmatrix}
> $$
> </p>
> ```
> 
> 🔗https://github.com/sunt-programator/CodeIT

Thanks a lot! It worked for me.
