### ISSUE TITLE
Music shortcode 不显示播放器，请问这个自定义的shortcode该如何使用？

### ISSUE THREAD

**Issue by ximiTech** [dillonzq/LoveIt#562]
### Describe the bug 描述你遇到的错误
一段简短的对于你遇到的错误的描述.

在md文件中直接使用music shortcode，生成的html中并没有显示出播放器来。

### Expected behavior 期待的行为
一段简短的对于你期待的行为的描述.

正常出现播放器。

### Build Environment 构建环境

- OS: [e.g. Windows 10, macOS, Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [e.g. 0.69.0]

Windows 7
Hugo 0.78.2

**Comment by uPagge** [comment]
@ximiTech Since the developer has unfortunately abandoned the project :disappointed:, I would like to take responsibility for its support and development in the future.

I focused on adding new features, refreshed the design of the posts, fixed the bugs I found. 
There were so many changes (the ability to choose a separate design for the post, breadcrumbs, a new comment system and much more), and so much to do, that I decided to give the template a **new name uBlogger.**

**I will be glad if you look at it, you may like the updated design.**
-- -- -- -- --
:link: -> https://github.com/uPagge/uBlogger.

**Comment by victor-pogor** [comment]
Hi @ximiTech.

Can you provide please an example of the music shortcode that you used?

**Comment by ximiTech** [comment]
使用hugo 0.74版本，并且config.toml中添加了一个空的第三方库文件的 CDN 设置，music模块可以显示了。

**Comment by dahangda** [comment]
> 使用hugo 0.74版本，并且config.toml中添加了一个空的第三方库文件的 CDN 设置，music模块可以显示了。

不会配置呀老哥。下图改哪个地方呀？
<img width="782" alt="image" src="https://user-images.githubusercontent.com/13567648/186587102-99751e69-8f2b-4408-a294-70cca955664a.png">
