### ISSUE TITLE
Enchacement - Shall we create a fork and maintain it?

### ISSUE THREAD

**Issue by raulcorreia7** [dillonzq/LoveIt#563]
Hello everyone,

Seems the project is a bit dead,
Shall we create a fork and maintain it?
We need to a have to funnel people to the new project.

King Regards,
Raúl

**Comment by nekr0z** [comment]
Discussion in #514 didn't reveal many volunteers.

**Comment by uPagge** [comment]
I am preparing for support while trying to reach the developer.

While studying the code, adding new functions, in the next two or three weeks I will show my fork

**Comment by raulcorreia7** [comment]
Well, we can maybe do a joint effort.
Any more volunteers, or just three people with interest so far?

**Comment by uPagge** [comment]
There is another person who is often involved in PR

https://github.com/khusika

Maybe he will connect

**Comment by uPagge** [comment]
I tried to contact the developer via telegram, but he has not been there for a month, it seems to me that something happened :(

**Comment by uPagge** [comment]
On the question of changes.  While you can evaluate the visible changes on my website blog.upagge.ru

Of the most noticeable is the reworking of the appearance of posts, adding bread crumbs, I also took all the best PRs and added them to myself.

Now I am carefully studying the code to understand the author's idea.  As I said, I think I will open my fork within two weeks

**Comment by uPagge** [comment]
@raulcorreia7  Since the developer has unfortunately abandoned the project :disappointed:, I would like to take responsibility for its support and development in the future.

I focused on adding new features, refreshed the design of the posts, fixed the bugs I found. 
There were so many changes (the ability to choose a separate design for the post, breadcrumbs, a new comment system and much more), and so much to do, that I decided to give the template a **new name uBlogger.**

**I will be glad if you look at it, you may like the updated design.**
-- -- -- -- --
:link: -> https://github.com/uPagge/uBlogger.

**Comment by raulcorreia7** [comment]
I'm taking a look into the new theme.
If i can i'll try to add/help.

**Comment by victor-pogor** [comment]
Hi all! I love this theme and it's sad that this theme is not supported. I also created the [CodeIT](https://github.com/sunt-programator/CodeIT) theme and I plan to maintain and improve it, which means we have two successors and this theme will live 🙂.

**Comment by dillonzq** [comment]
See https://github.com/dillonzq/LoveIt/issues/672
