### ISSUE TITLE
forestry.io - insert a unique path for images

### ISSUE THREAD

**Issue by elax46** [dillonzq/LoveIt#569]
Hi maybe I'll ask a useless question but I'm experimenting with hugo and this theme recently

Since I use forestry.io how do I set a path for images? (example: / static / uploads) since the test site creates a folder for the single post with the insertion of the image

**Comment by uPagge** [comment]
If you are talking about illustrations for posts, then you can put them directly into the post folder. i do just that

![изображение](https://user-images.githubusercontent.com/40397740/104075929-81ce9880-5225-11eb-8db0-67ce56941117.png)

-- -- -- -- --
Since the author of this topic does not come out on contact since May, I took the liberty of supporting and developing this topic.

I have already added new features, and I'm not going to stop. My repository is here: github.com/upagge/ublogger

**Comment by elax46** [comment]
hello thanks for the answer yes I'm talking about the featured image of the post. The management of the insertion of contents I do it through forestry.io for a matter of practicality and therefore I wanted to insert a single path for all the images and not upload each image in a folder dedicated to the single article because forestry allows you to upload them in one static path and not being able to change it for each post I don't know if the theme allows such a thing or it is mandatory to do the path as you entered it

**Comment by uPagge** [comment]
All images can be added to static. But in my opinion it is not convenient

**Comment by elax46** [comment]
I understand but wanting to use a CMS, since whoever has to use the site is not really that practical it was easier such a thing but it is not possible to make the theme understand to use a single path?
