### ISSUE TITLE
Overwrite description of posts d'ont appear in home

### ISSUE THREAD

**Issue by x1n5h3n** [dillonzq/LoveIt#85]
I've put a description in my post (description: "My description"), but it's not modifying the description of the post when listed in the home page.
Is it a bug or an error of my understanding of the purpose of "description" parameter of a post ?

**Comment by dillonzq** [comment]
Hi, @x1n5h3n 
It has been fixed in #93 .
But the behavior is different now. Only when your summary is empty, the description could be used.
Your should place `<!--more-->`  before your content to make the summary empty. Like this:
![image](https://user-images.githubusercontent.com/30786232/75056141-59588580-5511-11ea-9da9-dda5d42ea156.png)
